function [p,I,gamma] = Modelparameterfunctions(Km,Vm,C_B,C_H,C_G,C_L,C_K,...
    C_MP,C_AP,p,J,L,I,QQ,II,gamma,mu,Q,V)
%Script that calculate all the parametervalues, that changes during the
%simulation of the model, as they depend on current concentrations
%of metabolites.
%The script is called inside the model script, and provides the
%reaction vectors, that are multiplied by the Stoichiometric Matrix, as
%well as values used in the Insulin and Glucagon submodels.

%Insulin and Glucagon ratios that are used later
I_H = C_H(end-1);
Gamma_H = C_H(end);
%Tissue specific hormonal control
I_L = C_L(end-1);
Gamma_L = C_L(end);
I_MP = C_MP(end-1);
I_AP = C_AP(end-1);
Gamma_AP = C_AP(end);


%%%% Insulin submodel %%%%
%Insulin release equations:
I.X = (18*C_H(1))^I.beta_pir1 / (I.beta_pir2^I.beta_pir1 + ...
        I.beta_pir3 * (18*C_H(1))^I.beta_pir4);
I.Y = I.X^I.beta_pir5;
I.P_inf = I.Y;
I.S = (I.M_1 * I.Y + I.M_2 * min(0,I.X-II))*QQ;
I.r_PIR = I.S / I.S_B * I.r_B_PIR;
%Insulin clearance:
I.r_LIC = I.F_LIC * (Q.A * I_H + Q.G * C_G(end-1) + I.r_PIR);
I.r_KIC = I.F_KIC * Q.K * I_H;
I.r_MIC = I.F_PIC * Q.MP * I_H;
I.r_AIC = I.F_PIC * Q.AP * I_H;

%%%% Glucagon submodel %%%%
gamma.r_PgammaC = gamma.r_MgammaC * Gamma_H;
gamma.M_G_PgammaR = 2.93 - 2.10 * tanh(4.18 * (C_H(1) / gamma.G_B_H - 0.61));
gamma.M_I_PgammaR = 1.31 - 0.61 * tanh(1.06 * (I_H / gamma.I_B_H - 0.47));
gamma.r_PgammaR = gamma.M_G_PgammaR * gamma.M_I_PgammaR * gamma.r_B_PgammaR;


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%% Reaction Rates %%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%Indexes used correspond to metabolites in the vector:
%[GLC,G6P,GLY,GA3P,PYR,ACoA,OXA,CIT,LAC,AA,FFA,TGL,GLR,KET,PRO,TGL_AP,INS,GLU]
%All rates are in [mM/min]
%Entries = 0 in the reaction vectors, means the reaction doesn't occur in
%the corresponding tissue.

%%%%% Brain Reaction Rates %%%%%
r_B = [Vm.B_GLC_G6P*C_B(1) / (Km.B_GLC_G6P + C_B(1)); 0;...
Vm.B_G6P_GA3P*C_B(2) / (Km.B_G6P_GA3P + C_B(2)); 0;...
0; 0;...
Vm.B_GA3P_PYR*C_B(4) / (Km.B_GA3P_PYR + C_B(4)); 0;...
Vm.B_PYR_LAC*C_B(5) / (Km.B_PYR_LAC + C_B(5)); Vm.B_LAC_PYR*C_B(9) / (Km.B_LAC_PYR + C_B(9));...
0; 0;...
Vm.B_PYR_ACoA*C_B(5) / (Km.B_PYR_ACoA + C_B(5)); Vm.B_ACoA_OXA_CIT*C_B(6)*C_B(7) / (Km.B_ACoA_OXA_CIT + C_B(6)*C_B(7));...
Vm.B_CIT_OXA*C_B(8) / (Km.B_CIT_OXA + C_B(8)); Vm.B_OXA_PYR*C_B(7) / (Km.B_OXA_PYR + C_B(7));...
Vm.B_PYR_OXA*C_B(5) / (Km.B_PYR_OXA + C_B(5)); 0;...
0; 0;...
0; 0;...
0; Vm.B_KET_ACoA*C_B(14) / (Km.B_KET_ACoA + C_B(14));...
0; 0; 0; 0; 0; 0; 0];

%%%%% Heart Reaction Rates %%%%%
r_H = [Vm.H_GLC_G6P*C_H(1) / (Km.H_GLC_G6P + C_H(1)); 0;...
Vm.H_G6P_GA3P*C_H(2) / (Km.H_G6P_GA3P + C_H(2));0;...
0; 0;...
Vm.H_GA3P_PYR*C_H(4) / (Km.H_GA3P_PYR + C_H(4)); 0;...
Vm.H_PYR_LAC*C_H(5) / (Km.H_PYR_LAC + C_H(5)); Vm.H_LAC_PYR*C_H(9) / (Km.H_LAC_PYR + C_H(9));...
0; 0;...
Vm.H_PYR_ACoA*C_H(5) / (Km.H_PYR_ACoA + C_H(5)); Vm.H_ACoA_OXA_CIT*C_H(6)*C_H(7) / (Km.H_ACoA_OXA_CIT + C_H(6)*C_H(7));...
Vm.H_CIT_OXA*C_H(8) / (Km.H_CIT_OXA + C_H(8)); Vm.H_OXA_PYR*C_H(7) / (Km.H_OXA_PYR + C_H(7));...
Vm.H_PYR_OXA*C_H(5) / (Km.H_PYR_OXA + C_H(5)); 0;...
0; 0;...
Vm.H_TGL_GLR_FFA*C_H(12) / (Km.H_TGL_GLR_FFA + C_H(12)); Vm.H_FFA_ACoA*C_H(11) / (Km.H_FFA_ACoA + C_H(11));...
0; Vm.H_KET_ACoA*C_H(14) / (Km.H_KET_ACoA + C_H(14));...
0; 0; 0; 0; 0; 0; 0];

%%%%% Gut Reaction Rates %%%%%
r_G = [Vm.G_GLC_G6P*C_G(1) / (Km.G_GLC_G6P + C_G(1)); 0;...
Vm.G_G6P_GA3P*C_G(2) / (Km.G_G6P_GA3P + C_G(2)); 0;...
0; 0;...
Vm.G_GA3P_PYR*C_G(4) / (Km.G_GA3P_PYR + C_G(4)); 0;...
Vm.G_PYR_LAC*C_G(5) / (Km.G_PYR_LAC + C_G(5)); Vm.G_LAC_PYR*C_G(9) / (Km.G_LAC_PYR + C_G(9));...
0; Vm.G_AA_PYR*C_G(10) / (Km.G_AA_PYR + C_G(10));...
Vm.G_PYR_ACoA*C_G(5) / (Km.G_PYR_ACoA + C_G(5)); Vm.G_ACoA_OXA_CIT*C_G(6)*C_G(7) / (Km.G_ACoA_OXA_CIT + C_G(6)*C_G(7));...
Vm.G_CIT_OXA*C_G(8) / (Km.G_CIT_OXA + C_G(8)); Vm.G_OXA_PYR*C_G(7) / (Km.G_OXA_PYR + C_G(7));...
Vm.G_PYR_OXA*C_G(5) / (Km.G_PYR_OXA + C_G(5)); 0;...
0; 0;...
0; Vm.G_FFA_ACoA*C_G(11) / (Km.G_FFA_ACoA + C_G(11));...
0; 0;...
0; 0; 0; 0; 0; 0; 0];

%%%%% Liver Reaction Rates %%%%%
r_L = [(I_L / I.L_SS)^mu.L_GLC_G6P * Vm.L_GLC_G6P*C_L(1) / (Km.L_GLC_G6P + C_L(1)); Vm.L_G6P_GLC*C_L(2) / (Km.L_G6P_GLC + C_L(2));...
(I_L/I.L_SS * gamma.L_SS/Gamma_L)^mu.L_G6P_GA3P * Vm.L_G6P_GA3P*C_L(2) / (Km.L_G6P_GA3P + C_L(2)); (Gamma_L/gamma.L_SS * I.L_SS/I_L)^mu.L_GA3P_G6P * Vm.L_GA3P_G6P*C_L(4) / (Km.L_GA3P_G6P + C_L(4));...
(I_L/I.L_SS * gamma.L_SS/Gamma_L)^mu.L_G6P_GLY * Vm.L_G6P_GLY*C_L(2) / (Km.L_G6P_GLY + C_L(2)); (Gamma_L/gamma.L_SS * I.L_SS/I_L)^mu.L_GLY_G6P * Vm.L_GLY_G6P*C_L(3) / (Km.L_GLY_G6P + C_L(3));...
Vm.L_GA3P_PYR*C_L(4) / (Km.L_GA3P_PYR + C_L(4)); Vm.L_PYR_GA3P*C_L(5) / (Km.L_PYR_GA3P + C_L(5));...
Vm.L_PYR_LAC*C_L(5) / (Km.L_PYR_LAC + C_L(5)); Vm.L_LAC_PYR*C_L(9) / (Km.L_LAC_PYR + C_L(9));...
0; Vm.L_AA_PYR*C_L(10) / (Km.L_AA_PYR + C_L(10));...
(I_L / I.L_SS)^mu.L_PYR_ACoA * Vm.L_PYR_ACoA*C_L(5) / (Km.L_PYR_ACoA + C_L(5)); Vm.L_ACoA_OXA_CIT*C_L(6)*C_L(7) / (Km.L_ACoA_OXA_CIT + C_L(6)*C_L(7));...
Vm.L_CIT_OXA*C_L(8) / (Km.L_CIT_OXA + C_L(8)); Vm.L_OXA_PYR*C_L(7) / (Km.L_OXA_PYR + C_L(7));...
Vm.L_PYR_OXA*C_L(5) / (Km.L_PYR_OXA + C_L(5)); 0;...
Vm.L_GLR_GA3P*C_L(13) / (Km.L_GLR_GA3P + C_L(13)); Vm.L_GLR_FFA_TGL*C_L(11)*C_L(13) / (Km.L_GLR_FFA_TGL + C_L(11)*C_L(13));...
0; Vm.L_FFA_ACoA*C_L(11) / (Km.L_FFA_ACoA + C_L(11));...
(I_L / I.L_SS)^mu.L_ACoA_FFA * Vm.L_ACoA_FFA*C_L(6) / (Km.L_ACoA_FFA + C_L(6)); 0;...
Vm.L_ACoA_KET*C_L(6) / (Km.L_ACoA_KET + C_L(6)); 0;...
0; 0;...
0; (I.r_PIR - I.r_LIC)/V.L; (gamma.r_PgammaR - gamma.r_PgammaC)/V.L];

%%%%% Kidney Reaction Rates %%%%%
r_K = [Vm.K_GLC_G6P*C_K(1) / (Km.K_GLC_G6P + C_K(1)); Vm.K_G6P_GLC*C_K(2) / (Km.K_G6P_GLC + C_K(2));...
Vm.K_G6P_GA3P*C_K(2) / (Km.K_G6P_GA3P + C_K(2)); Vm.K_GA3P_G6P*C_K(4) / (Km.K_GA3P_G6P + C_K(4));...
0; 0;...
Vm.K_GA3P_PYR*C_K(4) / (Km.K_GA3P_PYR + C_K(4)); Vm.K_PYR_GA3P*C_K(5) / (Km.K_PYR_GA3P + C_K(5));...
Vm.K_PYR_LAC*C_K(5) / (Km.K_PYR_LAC + C_K(5)); Vm.K_LAC_PYR*C_K(9) / (Km.K_LAC_PYR + C_K(9));...
0; Vm.K_AA_PYR*C_K(10) / (Km.K_AA_PYR + C_K(10));...
Vm.K_PYR_ACoA*C_K(5) / (Km.K_PYR_ACoA + C_K(5)); Vm.K_ACoA_OXA_CIT*C_K(6)*C_K(7) / (Km.K_ACoA_OXA_CIT + C_K(6)*C_K(7));...
Vm.K_CIT_OXA*C_K(8) / (Km.K_CIT_OXA + C_K(8)); Vm.K_OXA_PYR*C_K(7) / (Km.K_OXA_PYR + C_K(7));...
Vm.K_PYR_OXA*C_K(5) / (Km.K_PYR_OXA + C_K(5)); 0;...
Vm.K_GLR_GA3P*C_K(13) / (Km.K_GLR_GA3P + C_K(13)); 0;...
0; Vm.K_FFA_ACoA*C_K(11) / (Km.K_FFA_ACoA + C_K(11));...
0; 0;...
0; 0;...
0; 0;...
0; -I.r_KIC/V.K; 0];

%%%%% Muscle Reaction Rates %%%%%
r_MP = [(I_MP / I.MP_SS)^mu.MP_GLC_G6P * Vm.MP_GLC_G6P*C_MP(1) / (Km.MP_GLC_G6P + C_MP(1)); 0;...
(I_MP / I.MP_SS)^mu.MP_G6P_GA3P * Vm.MP_G6P_GA3P*C_MP(2) / (Km.MP_G6P_GA3P + C_MP(2)); 0;...
(I_MP / I.MP_SS)^mu.MP_G6P_GLY * Vm.MP_G6P_GLY*C_MP(2) / (Km.MP_G6P_GLY + C_MP(2)); (I.MP_SS / I_MP)^mu.MP_GLY_G6P * Vm.MP_GLY_G6P*C_MP(3) / (Km.MP_GLY_G6P + C_MP(3));...
Vm.MP_GA3P_PYR*C_MP(4) / (Km.MP_GA3P_PYR + C_MP(4)); 0;...
Vm.MP_PYR_LAC*C_MP(5) / (Km.MP_PYR_LAC + C_MP(5)); Vm.MP_LAC_PYR*C_MP(9) / (Km.MP_LAC_PYR + C_MP(9));...
Vm.MP_PYR_AA*C_MP(5) / (Km.MP_PYR_AA + C_MP(5)); 0;...
(I_MP / I.MP_SS)^mu.MP_PYR_ACoA * Vm.MP_PYR_ACoA*C_MP(5) / (Km.MP_PYR_ACoA + C_MP(5)); Vm.MP_ACoA_OXA_CIT*C_MP(6)*C_MP(7) / (Km.MP_ACoA_OXA_CIT + C_MP(6)*C_MP(7));...
Vm.MP_CIT_OXA*C_MP(8) / (Km.MP_CIT_OXA + C_MP(8)); Vm.MP_OXA_PYR*C_MP(7) / (Km.MP_OXA_PYR + C_MP(7));...
Vm.MP_PYR_OXA*C_MP(5) / (Km.MP_PYR_OXA + C_MP(5)); 0;...
0; 0;...
Vm.MP_TGL_GLR_FFA*C_MP(12) / (Km.MP_TGL_GLR_FFA + C_MP(12)); Vm.MP_FFA_ACoA*C_MP(11) / (Km.MP_FFA_ACoA + C_MP(11));...
0; Vm.MP_KET_ACoA*C_MP(14) / (Km.MP_KET_ACoA + C_MP(14));...
0; (I_MP / I.MP_SS)^mu.MP_AA_PRO * Vm.MP_AA_PRO*C_MP(10) / (Km.MP_AA_PRO + C_MP(10));...
(I.MP_SS / I_MP)^mu.MP_PRO_AA * Vm.MP_PRO_AA*C_MP(15) / (Km.MP_PRO_AA + C_MP(15)); 0;...
0; -I.r_MIC/V.MP; 0];

%%%%% Adipose Reaction Rates %%%%%
r_AP = [(I_AP / I.AP_SS)^mu.AP_GLC_G6P * Vm.AP_GLC_G6P*C_AP(1) / (Km.AP_GLC_G6P + C_AP(1)); 0;...
Vm.AP_G6P_GA3P*C_AP(2) / (Km.AP_G6P_GA3P + C_AP(2)); 0;...
0; 0;...
Vm.AP_GA3P_PYR*C_AP(4) / (Km.AP_GA3P_PYR + C_AP(4)); 0;...
Vm.AP_PYR_LAC*C_AP(5) / (Km.AP_PYR_LAC + C_AP(5)); Vm.AP_LAC_PYR*C_AP(9) / (Km.AP_LAC_PYR + C_AP(9));...
0; 0;...
Vm.AP_PYR_ACoA*C_AP(5) / (Km.AP_PYR_ACoA + C_AP(5)); Vm.AP_ACoA_OXA_CIT*C_AP(6)*C_AP(7) / (Km.AP_ACoA_OXA_CIT + C_AP(6)*C_AP(7));...
Vm.AP_CIT_OXA*C_AP(8) / (Km.AP_CIT_OXA + C_AP(8)); Vm.AP_OXA_PYR*C_AP(7) / (Km.AP_OXA_PYR + C_AP(7));...
Vm.AP_PYR_OXA*C_AP(5) / (Km.AP_PYR_OXA + C_AP(5)); Vm.AP_GA3P_GLR*C_AP(4) / (Km.AP_GA3P_GLR + C_AP(4));...
0; 0;...
(I_AP / I.AP_SS)^mu.AP_TGL_GLR_FFA * Vm.AP_TGL_GLR_FFA*C_AP(12) / (Km.AP_TGL_GLR_FFA + C_AP(12)); Vm.AP_FFA_ACoA*C_AP(11) / (Km.AP_FFA_ACoA + C_AP(11));...
Vm.AP_ACoA_FFA*C_AP(6) / (Km.AP_ACoA_FFA + C_AP(6)); 0;...
0; 0;...
0; (I_AP / I.AP_SS)^mu.AP_GLR_FFA_TGL_AP*Vm.AP_GLR_FFA_TGL_AP*C_AP(11)*C_AP(13) / (Km.AP_GLR_FFA_TGL_AP + C_AP(11)*C_AP(13));...
(Gamma_AP/gamma.AP_SS * I.AP_SS/I_AP)^mu.AP_TGL_AP_GLR_FFA * Vm.AP_TGL_AP_GLR_FFA*C_AP(16) / (Km.AP_TGL_AP_GLR_FFA + C_AP(16)); -I.r_AIC/V.AP; 0];

%%%% Calculating production rate vectors %%%%
p.R_B = (p.T_B * p.S)' * p.T_B * r_B;
p.R_H = (p.T_H * p.S)' * p.T_H * r_H;
p.R_G = (p.T_G * p.S)' * p.T_G * r_G;
p.R_L = (p.T_L * p.S)' * p.T_L * r_L;
p.R_K = (p.T_K * p.S)' * p.T_K * r_K;
p.R_MP = (p.T_MP * p.S)' * p.T_MP * r_MP;
p.R_AP = (p.T_AP * p.S)' * p.T_AP * r_AP;

%%%% SIMO-model %%%%
%Parameters, for the uptake of nutrients
GI_parms = p.GI_k_gj .* J + p.GI_k_gl .* L;
p.GI_GLC = GI_parms(1);
p.GI_AA = GI_parms(2);
p.GI_TGL = GI_parms(3);

%%% To simulate steady state %%%
% p.R_L(3) = 0;
% p.R_MP(3) = 0;
% p.R_MP(15) = 0;
% p.R_AP(16) = 0;

end